apiVersion: 1
datasources:
  - name: InfluxDB
    uid: influxdb-forest-risk
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: forest-risk
      defaultBucket: metrics
      tlsSkipVerify: true
    secureJsonData:
      token: forest-risk-influx-token-2024
    isDefault: true
    editable: false